width: 800
height: 800
luminosity-label: '%1$.2f fb^{-1} (13 TeV)'
experiment: "CMS"
extra-label: "Preliminary"

#root: '/home/fynu/swertz/scratch/CMSSW_7_6_3_patch2/src/cp3_llbb/HHTools/condor/160611_all_0/condor/output/'
#root: '/home/fynu/swertz/scratch/CMSSW_7_6_3_patch2/src/cp3_llbb/HHTools/condor/160614_mllFlav_0/condor/output/'
#root: '/home/fynu/swertz/scratch/CMSSW_7_6_3_patch2/src/cp3_llbb/HHTools/condor/160614_highBDT_2D_0/condor/output/'
#root: '/home/fynu/swertz/scratch/CMSSW_7_6_3_patch2/src/cp3_llbb/HHTools/condor/160615_allGood_0/condor/output/'
#root: '/home/fynu/sbrochet/scratch/Framework/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/160701_all_newjer_0/condor/output/'
#root: '/home/fynu/sbrochet/scratch/Framework/CMSSW_7_6_5/src/cp3_llbb/HHTools/histFactory_hh/160706_all_newjer_newtraining_fixedcluster7_0//condor/output/'
#root: '/home/fynu/swertz/scratch/CMSSW_7_6_3_patch2/src/cp3_llbb/HHTools/condor/160624_new2Dbinnings_0/condor/output/'
root: '/home/fynu/swertz/scratch/CMSSW_7_6_3_patch2/src/cp3_llbb/HHTools/condor/160714_rebinned_0/condor/output/'

luminosity: 2300  # according to brilcalc 
luminosity-error: 0.027
blinded-range-fill-color: "16" #"#29556270"
blinded-range-fill-style: 3004

yields-table-align: v
